In [2]:
from collections import Counter

words = ["apple", "banana", "cherry", "apple", "mango", "cherry"]
word_counts = Counter(words)

print(word_counts)

Counter({'apple': 2, 'cherry': 2, 'banana': 1, 'mango': 1})


In [3]:
most_common = word_counts.most_common(2)  # Output: [('apple', 2), ('cherry', 2)]


In [4]:
most_common


[('apple', 2), ('cherry', 2)]

In [5]:
len(most_common)

2

In [21]:
a = {w[0]: index+2 for index, w in enumerate(most_common)}
a

{'apple': 2, 'cherry': 3}

In [20]:
for index, w in enumerate(most_common):
    print("index ->", index, "w ->", w)
    print(w[0], index+2)

index -> 0 w -> ('apple', 2)
apple 2
index -> 1 w -> ('cherry', 2)
cherry 3


In [15]:
a

{'apple': 2, 'cherry': 3}

In [22]:
index_dict = {v: k for k, v in a.items()}

In [23]:
index_dict

{2: 'apple', 3: 'cherry'}

In [25]:
UNK = 0 # unknow word-id
PAD = 1 # padding word-id
BATCH_SIZE = 64

a["UNK"] = UNK
a["PAD"] = PAD

In [26]:
a

{'apple': 2, 'cherry': 3, 'UNK': 0, 'PAD': 1}

# scatter and gather method

In [2]:
import torch

t = torch.zeros(3,4)
t

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
indices = torch.tensor(
    [
        [0,1,2,3],
        [1,2,0,3]
    ]
)

In [22]:
values = torch.tensor(
    [
        1
    
    ]
)

values = values.type_as(t)

In [23]:
t.scatter_(1, indices.unsqueeze(1), values)
print(t)

RuntimeError: Index tensor must have the same number of dimensions as self tensor

In [26]:
indices.unsqueeze(0).shape

torch.Size([1, 2, 4])

# Shallow cp and deep cp


In [27]:
import copy

In [28]:
a = [1,2,3,4]


In [29]:
b = copy.copy(a)
b

[1, 2, 3, 4]

In [30]:
b[0]=10
b

[10, 2, 3, 4]

In [31]:
a

[1, 2, 3, 4]

In [32]:
import copy

# Create a list
original_list = [1, 2, [3, 4]]

# Shallow copy
shallow_copy_list = copy.copy(original_list)

# Deep copy
deep_copy_list = copy.deepcopy(original_list)

# Modify the original list and nested list
original_list[2][0] = 5

# Print the original list, shallow copy, and deep copy
print("Original List:", original_list)
print("Shallow Copy List:", shallow_copy_list)
print("Deep Copy List:", deep_copy_list)

Original List: [1, 2, [5, 4]]
Shallow Copy List: [1, 2, [5, 4]]
Deep Copy List: [1, 2, [3, 4]]


# fill_

In [33]:
import torch

# Create a tensor with random values
data = torch.randn(3, 4)  # Creates a 3x4 tensor with random numbers
print("Original tensor:\n", data)

# Fill the tensor with a specific value (5)
data.fill_(5)
print("\nTensor after filling with 5:\n", data)

# Fill the tensor with another value based on calculations
smoothing_factor = 0.1
size = 5
uniform_value = smoothing_factor / (size - 2)
data.fill_(uniform_value)
print("\nTensor filled with calculated uniform value:\n", data)


Original tensor:
 tensor([[ 1.8496, -0.0367,  0.5297,  0.1353],
        [ 0.8572, -1.1632,  0.5359,  0.3767],
        [-0.7597,  0.5982,  1.1204,  1.5685]])

Tensor after filling with 5:
 tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

Tensor filled with calculated uniform value:
 tensor([[0.0333, 0.0333, 0.0333, 0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333]])


In [3]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])